# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Install dependencies
      run: |
        go get google.golang.org/protobuf/proto
        go get github.com/go-gota/gota/series
        go get github.com/go-gota/gota/dataframe
        go install github.com/golang/protobuf/protoc-gen-go
        
    - name: Install native GenomicsDB
      working-directory: ${{ github.workspace }}/install-genomicsdb
      run: |
        go build -v ./...
        ./install-genomicsdb

    - name: Build and test
      working-directory:  ${{ github.workspace }}/bindings
      run: |
        go build -v ./...
        go test -v ./...
